### ISSUE TITLE
AttributeError: 'module' object has no attribute 'format_datetime'

### ISSUE THREAD

**Issue by bloedersack** [an0/Letterpress#9]
Hello,

i updated my files with last changed and have the following issus:

```
2015-11-18 20:11:26,719 - INFO - Site configure: {'date_format': '%m/%d/%Y', 'description': "blog", 'title': "blog", 'site_dir': '/var/www/blog/', 'base_url': 'http://url', 'markdown_ext': '.md', 'math_delimiter': '$'}
2015-11-18 20:11:26,722 - INFO - Build site
Traceback (most recent call last):
  File "/usr/lib/python3.2/letterpress.py", line 907, in <module>
    sys.exit(main())
  File "/usr/lib/python3.2/letterpress.py", line 757, in main
    build_site()
  File "/usr/lib/python3.2/letterpress.py", line 755, in build_site
    create_rss_feed(posts)
  File "/usr/lib/python3.2/letterpress.py", line 707, in create_rss_feed
    item_list.append(format(item_template, title=post.title, date=email.utils.format_datetime(post.date), permalink=post.permalink, content=post.content))
AttributeError: 'module' object has no attribute 'format_datetime'
```

I double check all files and tried installing email via pip/pip-3.2 without any result. Unfortunately i can not find the solution myself.

Best regards!

**Comment by an0** [comment]
email.utils.format_datetime is new in Python 3.3. So upgrade your Python.

**Comment by bloedersack** [comment]
That works!

Raspberry Pi (Debian Wheezy) repository has no Python3.3 and i installed it manually.

Thank you very much and keep it up.
